# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'competition_map.ui'
#
# Created by: PyQt5 UI code generator 5.15.5
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class CompetitionMapUi(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(504, 389)
        self.gridLayout = QtWidgets.QGridLayout(Form)
        self.gridLayout.setObjectName("gridLayout")
        self.location_map_layout = QtWidgets.QHBoxLayout()
        self.location_map_layout.setSpacing(0)
        self.location_map_layout.setObjectName("location_map_layout")
        self.location_widgets_layout = QtWidgets.QVBoxLayout()
        self.location_widgets_layout.setObjectName("location_widgets_layout")
        self.current_coordinates_label = QtWidgets.QLabel(Form)
        self.current_coordinates_label.setObjectName("current_coordinates_label")
        self.location_widgets_layout.addWidget(self.current_coordinates_label)
        self.send_coordinates_layout = QtWidgets.QGridLayout()
        self.send_coordinates_layout.setObjectName("send_coordinates_layout")
        self.x_label = QtWidgets.QLabel(Form)
        self.x_label.setObjectName("x_label")
        self.send_coordinates_layout.addWidget(self.x_label, 0, 0, 1, 1)
        self.send_x = QtWidgets.QLineEdit(Form)
        self.send_x.setObjectName("send_x")
        self.send_coordinates_layout.addWidget(self.send_x, 0, 1, 1, 1)
        self.y_label = QtWidgets.QLabel(Form)
        self.y_label.setObjectName("y_label")
        self.send_coordinates_layout.addWidget(self.y_label, 1, 0, 1, 1)
        self.send_y = QtWidgets.QLineEdit(Form)
        self.send_y.setObjectName("send_y")
        self.send_coordinates_layout.addWidget(self.send_y, 1, 1, 1, 1)
        self.location_widgets_layout.addLayout(self.send_coordinates_layout)
        self.send_location_button = QtWidgets.QPushButton(Form)
        self.send_location_button.setObjectName("send_location_button")
        self.location_widgets_layout.addWidget(self.send_location_button)
        self.go_cancel_button = QtWidgets.QPushButton(Form)
        self.go_cancel_button.setObjectName("go_cancel_button")
        self.location_widgets_layout.addWidget(self.go_cancel_button)
        self.location_list = QtWidgets.QTableView(Form)
        self.location_list.setObjectName("location_list")
        self.location_widgets_layout.addWidget(self.location_list)
        self.location_map_layout.addLayout(self.location_widgets_layout)
        self.competitionMap = QtWidgets.QGraphicsView(Form)
        self.competitionMap.setObjectName("competitionMap")
        self.location_map_layout.addWidget(self.competitionMap)
        self.location_map_layout.setStretch(0, 1)
        self.location_map_layout.setStretch(1, 3)
        self.gridLayout.addLayout(self.location_map_layout, 0, 0, 1, 1)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.current_coordinates_label.setText(_translate("Form", "Current x and y"))
        self.x_label.setText(_translate("Form", "x"))
        self.y_label.setText(_translate("Form", "y"))
        self.send_location_button.setText(_translate("Form", "Send Location"))
        self.go_cancel_button.setText(_translate("Form", "Go/Cancel"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
