# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'topic_controller.ui'
#
# Created by: PyQt5 UI code generator 5.15.5
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_TopicController(object):
    def setupUi(self, TopicController):
        TopicController.setObjectName("TopicController")
        TopicController.resize(216, 219)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(TopicController)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.lineEdit = QtWidgets.QLineEdit(TopicController)
        self.lineEdit.setObjectName("lineEdit")
        self.verticalLayout.addWidget(self.lineEdit)
        self.pushButton = QtWidgets.QPushButton(TopicController)
        self.pushButton.setObjectName("pushButton")
        self.verticalLayout.addWidget(self.pushButton)
        self.listView = QtWidgets.QListView(TopicController)
        self.listView.setObjectName("listView")
        self.verticalLayout.addWidget(self.listView)
        self.verticalLayout_2.addLayout(self.verticalLayout)

        self.retranslateUi(TopicController)
        QtCore.QMetaObject.connectSlotsByName(TopicController)

    def retranslateUi(self, TopicController):
        _translate = QtCore.QCoreApplication.translate
        TopicController.setWindowTitle(_translate("TopicController", "Form"))
        self.pushButton.setText(_translate("TopicController", "PushButton"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    TopicController = QtWidgets.QWidget()
    ui = Ui_TopicController()
    ui.setupUi(TopicController)
    TopicController.show()
    sys.exit(app.exec_())
